spring.application.name=kotlin-spring-boot-sample-app
testframework.scan-packages=no.kompilator.kotlinapp.tests

# -----------------------------------------------------------------------
# Test Framework ? Reporting Plugin
# -----------------------------------------------------------------------
testframework.reporting.run-on-startup=true
# testframework.reporting.output-dir=build/test-reports
# testframework.reporting.formats=JUNIT_XML,OPEN_TEST_REPORTING_XML,JSON
